### ISSUE TITLE
Add hover property on Button

### ISSUE THREAD

**Issue by shivam-sharma7** [shivam-sharma7/Expense-Tracker#11]
You can see the following botton img

![image](https://github.com/shivam-sharma7/Expense-Tracker/assets/91419219/a54ad1a0-bbe3-4822-a7c4-9b04e6eea826)

**Comment by shivam-sharma7** [comment]
@PratikMbade  would you like to give try?

**Comment by PratikMbade** [comment]
Assign me.

**Comment by shivam-sharma7** [comment]
@PratikMbade if you have any idea you can contribute. Thanks

**Comment by Aditya-768** [comment]
Can I contribute as well

**Comment by shivam-sharma7** [comment]
> Can I contribute as well

Yes

**Comment by smafsani** [comment]
Hi there! I noticed that the issue of adding the hover property to the Button is still open. If this problem is not solved yet, I would like to give it a try. Assigning me to this task. 👍

**Comment by shivam-sharma7** [comment]
@smafsani @PratikMbade you both assigned

**Comment by shivam-sharma7** [comment]
@Aditya-768 as well

**Comment by smafsani** [comment]
I am facing the follow problem while git pull upstream main
remote: Not Found
fatal: repository 'https://github.com/shivam-sharma7/Expense-Tracker/.git/' not found

**Comment by shivam-sharma7** [comment]
you need to set `git remote add upstream https://github.com/shivam-sharma7/Expense-Tracker.git`
